### ISSUE TITLE
Intel SGX Device Plugin returns error "permission denied" for OpenShift 4.13

### ISSUE THREAD

**Issue by tsadowsk** [intel/intel-technology-enabling-for-openshift#113]
### Summary
During installation of Intel SGX Device Plugin, an error occurs which states lack of access permissions for `kubelet.sock` socket from `intel-sgx-plugin` pod. This error happens in `OpenShift 4.13` and was not present in `OpenShift 4.12`.

### Detail
During installation of Intel SGX Device Plugin below error occurs:
```
oc -n openshift-operators logs pod/intel-sgx-plugin-ng262 -c intel-sgx-plugin
...
E0823 14:04:16.980975       1 manager.go:146] Failed to serve sgx.intel.com/provision: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: permission denied"
```

As a workaround, I added privileged access rights for the DaemonSet/Pod by using below command line:
```
oc -n openshift-operators edit ds/intel-sgx-plugin
```

After replacing:
```
securityContext:
    allowPrivilegeEscalation: false
```
with:
```
securityContext:
    privileged: true
```
started working. Most probably, such privileges escalation is not needed and can be limited to necessary only privileges.

Resolving this issue would be very helpful/beneficial because 4.13 is a current version of OpenShift, and this plugin works without any issues in OpenShift 4.12, which is a previous version.

Also, it would be great to make sure that such issue does not occur for the upcoming OpenShift version 4.14. Many thanks in advance!

**Comment by mregmi** [comment]
can you also upload /var/log/audit/audit.log

**Comment by hershpa** [comment]
Hi @tsadowsk! Thanks for submitting the issue and sharing all the details. 
We are aware of this regression issue on `OpenShift 4.13` and it is currently in triage. The behavior and analysis you elucidated above aligns with our observation. This issue was not present in  `OpenShift 4.12`. We are working to resolve it asap and have identified at least one component (a missing SELinux patch) in  `OpenShift 4.13`  that is responsible for this regression. 

Currently, our operator officially supports `OpenShift 4.13` (starting from `4.12.6`). We are working on [`v1.1.0`](https://github.com/intel/intel-technology-enabling-for-openshift/milestone/2) which will add support for `OpenShift 4.13` soon. Thanks for evaluating our operator on `OpenShift 4.13` and sharing your experience.

**Comment by tsadowsk** [comment]
@hershpa I sent /var/log/audit/audit.log directly to you as it might contain some sensitive information.

**Comment by mregmi** [comment]
Looks like SELinux policies in container-selinux changed between 4.12 and 4.13. We will investigate

**Comment by hershpa** [comment]
@mregmi Since this is a regression, can we create a RH ticket since these policies were missed in OCP 4.13 integration? The policies were already part of container-SELinux upstream project and were backported in OCP 4.12.

**Comment by hershpa** [comment]
Thanks @tsadowsk

**Comment by hershpa** [comment]
Can you try OCP `4.13.6`? That has the expected version of `container-selinux 2.215.0`.

**Comment by uMartinXu** [comment]
Thanks @hershpa! 
@tsadowsk After our investigating and syncing with RH, looks like the container-selinux 2.215.0 which includes the SeLinux policy needed by SGX Provisioning was not properly integrated into OCP-4.13.5.  RH told us this regression issue should have been resolved in 4.13.6. Could you please upgrade the OCP to this z release and have a try? If you still have a the issue, please let us know. Again, thank you very much for reporting this regression issue. :-)

**Comment by tsadowsk** [comment]
@uMartinXu @hershpa
I tried to run Intel Device Plugin with OpenShift 4.13.10.
Unfortunately, I still receive error about permissions denied to `/var/lib/kubelet/device-plugins/kubelet.sock`:
```
oc -n openshift-operators logs pod/intel-sgx-plugin-qqrtx
...
E0915 12:49:36.740419       1 manager.go:146] Failed to serve sgx.intel.com/enclave: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: permission denied"
...

oc version 
Client Version: 4.9.18
Server Version: 4.13.10
Kubernetes Version: v1.26.7+0ef5eae

oc get clusterversions
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.10   True        False         8d      Cluster version is 4.13.10

oc get no -owide
NAME      ROLES                  VERSION            OS-IMAGE                                                       KERNEL-VERSION                 CONTAINER-RUNTIME
master1   control-plane,master   v1.26.7+0ef5eae    Red Hat Enterprise Linux CoreOS 413.92.202308210212-0 (Plow)   5.14.0-284.28.1.el9_2.x86_64   cri-o://1.26.4-3.rhaos4.13.git615a02c.el9
worker1   worker                 v1.26.7+0ef5eae    Red Hat Enterprise Linux CoreOS 413.92.202308210212-0 (Plow)   5.14.0-284.28.1.el9_2.x86_64   cri-o://1.26.4-3.rhaos4.13.git615a02c.el9
```
Please let me know if you would need more info.

Could you please help?

**Comment by hershpa** [comment]
@tsadowsk thanks for the update. I am testing it on our end, let me see if I observe what you saw above.

**Comment by mythi** [comment]
FYI, @eadamsintel got everything deployed OK on 4.13.11.

**Comment by eadamsintel** [comment]
I got it to work by turning off SELinux which is not really a proper solution.

**Comment by Feelas** [comment]
Maybe this issue might be a generalized case of the [RHEL-3128 / Bug 2180456](https://issues.redhat.com/browse/RHEL-3128) bug?
Before JIRA migration it was ticket [Bug 2180456](https://bugzilla.redhat.com/show_bug.cgi?id=2180456).
Looks very close to what we are seeing.

**The similarities:**
1. Trying to access kubelet.sock from unprivileged container, which fails,
2. AVC issues reported by SELinux,
3. Kubelet is running with unconfined_service_t, which looks to be unexpected by Red Hat, 
4. In comment from March 27, "{ connectto }" denial is also reported as it is in our case.

**The differences:**
1. The bug is concerned specifically about Numa-aware scheduler.

Please note that at least one [Red Hat's own operator](https://issues.redhat.com/browse/OCPBUGS-10426) identified the mentioned [Bug 2180456](https://bugzilla.redhat.com/show_bug.cgi?id=2180456) issue as a long-term fix while applying short-term SELinux policy workarounds until Bug 2180456 is fixed.  The "{ connectto }" denial was also present there if you take a look at the comments.

**Comment by mregmi** [comment]
It looks like kubelet is running with incorrect label which is causing the SELinux access denial for plugins. 
kubelet should run as `kubelet_exec_t` and not `unconfined_service_t`

The bugzilla above touches on this issue but does not seem to provide solution/fix. Will investigate further on why its happening and check with RedHat too.

sh-5.1# ps -AZ | grep unconfined
system_u:system_r:unconfined_service_t:s0 8719 ? 00:24:50 kubelet
sh-5.1# ls  -Z /usr/bin/kubelet
system_u:object_r:kubelet_exec_t:s0 /usr/bin/kubelet

**Comment by hershpa** [comment]
Same issue for all 3 device plugins. We need to work with RH to resolve this regression/bug.

**Comment by mregmi** [comment]
actively being looked at by RedHat: https://issues.redhat.com/browse/OCPBUGS-20022

**Comment by hershpa** [comment]
Thanks @mregmi!

**Comment by mregmi** [comment]
@tsadowsk Which Intel Device Plugin Operator version are you using and where did you get the images from. Did you build it from IDPO upstream?

**Comment by hershpa** [comment]
We are waiting for a container SELinux patch to show up in a OCP 4.13.z and 4.14.z release. 
Refer to parent issue https://issues.redhat.com/browse/OCPBUGS-20022, 
4.13: https://issues.redhat.com/browse/OCPBUGS-22272 
4.14: https://issues.redhat.com/browse/OCPBUGS-22270.

**Comment by tsadowsk** [comment]
@hershpa I checked the issues i.e. https://issues.redhat.com/browse/OCPBUGS-20022 and looks like a blocker for this ticket, which was podman change: https://github.com/containers/container-selinux/pull/277 was merged. I noticed about it in ticket for RedHat.

**Comment by hershpa** [comment]
Waiting on Red Hat for visibility to target 4.13.z and 4.14.z release with the patch.

**Comment by brgavino** [comment]
Given that there's no LZ for this fix in upstream OCP, what's the suggested workaround for 4.13.11 (latest supported z per README)?

**Comment by mregmi** [comment]
Still waiting on fix to propagate to OCP 4.13 and 4.14 (https://issues.redhat.com/browse/OCPBUGS-20022)

**Issue root cause**:  Kubelet is running with wrong label in OCP 4.13 and higher

**Workaround**: Since the kubelet is running with wrong label in OCP 4.13 and beyond, we need to run SELinux in permissive mode as a workaround. To do this, In all the nodes, run the following command.
_#setenforce Permissive_

**Comment by mregmi** [comment]
This is fixed in 4.14.10

**Comment by brgavino** [comment]
Just a note here; even with SELinux set to "permissive" pods accessing the GPU through `/dev/dri/renderDXXX` will always pick up the default device `/dev/dri/renderD128`, even when that is not the pod's assigned resource, this results in errors when trying to use the device for any work (ie ffmpeg). This may be related to the SELinux config and could be added to the regression as a sanity check. 

This probably was resolved in this thread (https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1377) but the script that is used to check what device is usable (https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/gpu_plugin/render-device.sh) will always have the first device writable - so it's mostly useless for two GPUs on a single node.
